### ISSUE TITLE
Change DateDecodingStrategy & DateEncodingStrategy

### ISSUE THREAD

**Issue by muellers7** [egzonpllana/CodableFiles#3]
It would be nice if the Dateformat would be configurable. Maybe an optional parameter on load and save functions? Currently I dont see any other option

**Comment by egzonpllana** [comment]
hi @muellers7, would you mind describing what is the specific part of the library where we can add such functionality, please?

**Comment by muellers7** [comment]
Hey @egzonpllana,

thanks for you reply. 
First of all I have to admit that I'm pretty new to swift so maybe I misunderstand something.

My use case is that I want to load and save a json file that stores date values. From what I found, the following date formats are supported by JSONDecoder: 

ISO-8601: .iso8601
Seconds since 1970: .secondsSince1970
Milliseconds since 1970: .millisecondsSince1970
Custom: .formatted(formatter)
Seconds since 2001 (default: .deferredToDate  

JSONDecoder has a property "dateDecodingStrategy" 
and JSONEncoder has a property "dateEncodingStrategy"

so it would be possible to change the signature of the load function to (changed part in bold):

    func load<T: Decodable>(withFilename filename: String, atDirectory directory: CodableFilesDirectory = .defaultDirectory, **dateDecodingStrategy: JSONDecoder.DateDecodingStrategy = JSONDecoder.DateDecodingStrategy.deferredToDate**) throws -> T

And in addition it would be neccessary to instantiate the the JSONDecoder and set it in the function (
replace from line 115 in CodableFiles ):

        let jsonDecoder = JSONDecoder()
        jsonDecoder.dateDecodingStrategy = dateDecodingStrategy
        // Load the JSON data from the file and decode it to the desired type.
        let contentData = try Data(contentsOf: filePathURL)
        return try jsonDecoder.decode(T.self, from: contentData)


For save function it would be similar but we have to use the dateEncodingStrategy instead.


Greets
Stefan

**Comment by egzonpllana** [comment]
Your suggestion makes sense Stefan, thanks for explaining it. I will implement this feature this weekend and on Monday it will be ready. I will add a new parameter to provide the Encoder or Decoder for the save and load methods, so the developer can provide more options with customized decoder/encoder not just the dateDecodingStrategy.

Let me know what you think, or if you have something else in mind. Thanks! cc: @muellers7

**Comment by egzonpllana** [comment]
🚀  CodableFiles (1.1.1) successfully published
 📅  March 3rd (CET)
 
 👨‍💻 Changes:
 - Added new parameter to provide Encoder or Decoder instance.
 - Link to changes (v1.1.0 vs v1.1.1)
https://github.com/egzonpllana/CodableFiles/compare/1.1.0...1.1.1

**Comment by muellers7** [comment]
Thanks a lot!
